name: bangla_barta_surakha_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.14
  permission_handler: ^11.3.0
  flutter_sms_inbox: ^1.0.3
  flutter_contacts: ^1.1.9+2
  crypto: ^3.0.6
  http: ^1.2.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/test_icon.jpg
    - assets/images/
